#!/usr/bin/env bash
#  ____             _                         ____          _
# |  _ \  __ _ _ __| | ___ __   ___  ___ ___ / ___|___   __| | ___
# | | | |/ _' | '__| |/ / '_ \ / _ \/ __/ __| |   / _ \ / _' |/ _ \
# | |_| | (_| | |  |   <| | | |  __/\__ \__ \ |__| (_) | (_| |  __/
# |____/ \__,_|_|  |_|\_\_| |_|\___||___/___/\____\___/ \__,_|\___|
# -----------------------------------------------------------------
# https://darkncesscode.com
# https://github.com/codedarkness
# -----------------------------------------------------------------
#
#        FILE: sysact.sh
#       USAGE: ./sysact.sh | demenu for windows manager system
#
#
# DESCRIPTION: lock, restart, hibernate and shutdown your computer
#
#      AUTHOR: DarknessCode
#       EMAIL: admin@darknesscode.com
#
#     CREATED: 05-25-2020 6:10
#
# -----------------------------------------------------------------

# Check INIT
_initsys=$(ps -p 1 o comm=)

# dmenu
font="-fn 'Noto-14'"
DMENU="dmenu -i -c -l 6 $font -p"

# fzf
FZF="fzf --ansi --cycle --margin=0.5% --color=dark --height 100% --reverse --info=hidden --prompt"

declare -A main_menu
main_menu[Exit]="kill -TERM $(pidof -s dwm)"
main_menu[Lock Screen]="blurlock"
main_menu[Cancel]="notify-send Cancel by-user"
if [ $_initsys = "systemd" ]; then
main_menu[Reboot]="systemctl reboot"
main_menu[Shutdown]="systemctl poweroff"
elif [ $_initsys = "runit" ]; then
main_menu[Reboot]="loginctl reboot"
main_menu[Shutdown]="loginctl poweroff"
fi

menu() {
	printf '%s\n' "${!main_menu[@]}" | sort
}

main() {
  while : ; do
  	choice=$(menu | column -t -s "," -o " " | ${MENU} 'System Account : ' "$@") || exit 1

    if [ "$choice" ]; then
      ${main_menu["${choice}"]} && exit 0
    else
      echo "Program terminated." && exit 0
    fi
  done
}

noOpt=1
# If script is run with '-d', it will use 'dmenu'
# If script is run with '-f', it will use 'fzf'
while getopts "dfh" arg 2>/dev/null; do
    case "${arg}" in
        d) # shellcheck disable=SC2153
           MENU=${DMENU}
           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
        f) # shellcheck disable=SC2153
           MENU=${FZF}
           [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main ;;
        h) help ;;
        *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
    esac
    noOpt=0
done

# If script is run with NO argument, it will use 'dmenu'
[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
